### ISSUE TITLE
其他问题

### ISSUE THREAD

**Issue by Users00001** [tolumos/google-api-Continuous-dialogue-across-models#1]
很抱歉这种方式来打扰你，我的github copilot好像被封了，在社区了看到了你的回复说可以根据提示解封，我没收到任何邮件请问有其他方法嘛？

**Comment by lumosto** [comment]
直接提交工单等通知

**Comment by tolumos** [comment]
在GitHub支持里面提交工单，说copilot无故不能使用，然后根据提示解封就行
